// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

const firebaseConfig = {
  apiKey: "your-api-key",
  appId: "your-app-id",
  messagingSenderId: "676978108874",
  projectId: "musicapp-118ed",
  authDomain: "musicapp-118ed.firebaseapp.com",
  storageBucket: "musicapp-118ed.appspot.com",
  measurementId: "G-SE2RCL3EFQ"
};


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv3lEZPjDG0Xu94XCGwITggkQ9s0V_qWo',
    appId: '1:676978108874:android:d4ee40fa4234c50c908733',
    messagingSenderId: '676978108874',
    projectId: 'musicapp-118ed',
    storageBucket: 'musicapp-118ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqaZPmkrStFkpDsZzQVMCPHHAmXOWGtnw',
    appId: '1:676978108874:ios:ba0a07046f5fcf7a908733',
    messagingSenderId: '676978108874',
    projectId: 'musicapp-118ed',
    storageBucket: 'musicapp-118ed.appspot.com',
    iosBundleId: 'com.example.sptify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqaZPmkrStFkpDsZzQVMCPHHAmXOWGtnw',
    appId: '1:676978108874:ios:ba0a07046f5fcf7a908733',
    messagingSenderId: '676978108874',
    projectId: 'musicapp-118ed',
    storageBucket: 'musicapp-118ed.appspot.com',
    iosBundleId: 'com.example.sptify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqtHz3mqSoZvBxpVAqcehaaQmYK_ehbKo',
    appId: '1:676978108874:web:226a1c67eef3e372908733',
    messagingSenderId: '676978108874',
    projectId: 'musicapp-118ed',
    authDomain: 'musicapp-118ed.firebaseapp.com',
    storageBucket: 'musicapp-118ed.appspot.com',
    measurementId: 'G-DM97FZP1KT',
  );
}
